const armors = [
   {
      name: "noArmor",
      description: "nothing",
      damageReduction: 0,
      armorClass: 5,
      apRegen: 0,
      inPossession: true,
   },
   {
      name: "leather",
      description: "leather armor",
      damageReduction: 0,
      armorClass: 12,
      apRegen: 1,
      inPossession: false,
   },
   {
      name: "chainmail",
      description: "chainmail armor",
      damageReduction: 1,
      armorClass: 9,
      apRegen: 0,
      inPossession: true,
   },
   {
      name: "breastplate v1",
      description: "armor",
      damageReduction: 0,
      armorClass: 5,
      apRegen: 0,
      inPossession: true,
   },
   {
      name: "platemail",
      description: "platemail armor",
      damageReduction: 2,
      armorClass: 6,
      apRegen: -1,
      inPossession: false,
   },
];
