const opponentSchema = {
   name: String,
   level: Number,
   image: String,
   hitDie: Number,
   maxHp: Number,
   armor: Number,
   attack: Number,
   weapon: Number,
   strength: Number,
   dexterity: Number,
   endurance: Number,
   mind: Number,
   agility: Number,
   spirit: Number,
};
