const opponents = [
   {
      name: "Goblin",
      level: 1,
      image: "goblin2.jpg",
      hitDie: 6,
      maxHp: 6,
      armor: armors[0],
      attack: 2,
      weapon: weapons[0],
      strength: -1,
      dexterity: 1,
      endurance: -1,
      mind: -1,
      agility: 1,
      spirit: -1,
   },
   {
      name: "Orc",
      level: 2,
      image: "orc2.jpg",
      hitDie: 8,
      maxHp: 8,
      armor: armors[0],
      attack: 2,
      weapon: weapons[1],
      strength: 3,
      dexterity: 1,
      endurance: 2,
      mind: -1,
      agility: 1,
      spirit: 0,
   },
   {
      name: "Ogre",
      level: 3,
      image: "orc2.jpg",
      hitDie: 10,
      maxHp: 10,
      armor: armors[0],
      attack: 2,
      weapon: weapons[2],
      strength: 5,
      dexterity: 2,
      endurance: 4,
      mind: -1,
      agility: 0,
      spirit: 0,
   },
];
